'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
    FileText,
    ArrowLeft,
    Download,
    Mail,
    Eye,
    Calendar,
    AlertTriangle,
    CheckCircle,
    XCircle,
    ChevronDown,
    Loader2,
    RefreshCw
} from "lucide-react";
import Link from "next/link";
import { useRecentJHAs } from "@/hooks/use-api";
import { format } from "date-fns";
import ReactMarkdown from "react-markdown";

export default function ReportsPage() {
    const { data, isLoading, isError, refetch } = useRecentJHAs(50); // Get more for reports view
    const [expandedReport, setExpandedReport] = useState<string | null>(null);
    const [loadingMarkdown, setLoadingMarkdown] = useState<Record<string, boolean>>({});
    const [reportMarkdowns, setReportMarkdowns] = useState<Record<string, string>>({});

    const jhas = data?.jhas || [];

    const getDecisionColor = (decision: string) => {
        switch (decision) {
            case 'GO': return 'bg-green-500/10 text-green-600 border-green-500/30';
            case 'NO_GO': return 'bg-red-500/10 text-red-600 border-red-500/30';
            case 'GO_WITH_CONDITIONS': return 'bg-yellow-500/10 text-yellow-600 border-yellow-500/30';
            default: return 'bg-slate-500/10 text-slate-600 border-slate-500/30';
        }
    };

    const getDecisionIcon = (decision: string) => {
        switch (decision) {
            case 'GO': return <CheckCircle className="h-4 w-4" />;
            case 'NO_GO': return <XCircle className="h-4 w-4" />;
            case 'GO_WITH_CONDITIONS': return <AlertTriangle className="h-4 w-4" />;
            default: return <FileText className="h-4 w-4" />;
        }
    };

    const toggleReport = async (jhaId: string) => {
        if (expandedReport === jhaId) {
            setExpandedReport(null);
            return;
        }

        // If we don't have the markdown yet, fetch it
        if (!reportMarkdowns[jhaId]) {
            setLoadingMarkdown(prev => ({ ...prev, [jhaId]: true }));
            try {
                const response = await fetch(`/api/v1/jha/${jhaId}`);
                if (response.ok) {
                    const data = await response.json();
                    setReportMarkdowns(prev => ({
                        ...prev,
                        [jhaId]: data.markdown_report || generateFallbackMarkdown(data)
                    }));
                }
            } catch (error) {
                console.error('Failed to fetch report:', error);
            } finally {
                setLoadingMarkdown(prev => ({ ...prev, [jhaId]: false }));
            }
        }

        setExpandedReport(jhaId);
    };

    const generateFallbackMarkdown = (data: any) => {
        // Generate a basic markdown from the JHA data if markdown_report isn't available
        const summary = data.summary || {};
        const decision = summary.go_no_go_decision || 'UNKNOWN';
        const concerns = summary.primary_concerns || [];

        return `# Safety Analysis Report

## Executive Summary

**Decision:** ${decision}
**Risk Score:** ${data.risk_score || 'N/A'}
**Urgency Level:** ${data.urgency_level || 'N/A'}

## Primary Concerns

${concerns.map((c: string) => `- ${c}`).join('\n') || '- No concerns identified'}

---

*Report generated by Safety Companion AI*
`;
    };

    const handleDownload = (jhaId: string, projectName: string) => {
        const markdown = reportMarkdowns[jhaId];
        if (!markdown) return;

        const blob = new Blob([markdown], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `jha_report_${projectName.replace(/\s+/g, '_')}_${jhaId.slice(0, 8)}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleEmail = (jhaId: string, projectName: string) => {
        const markdown = reportMarkdowns[jhaId];
        if (!markdown) return;

        const subject = encodeURIComponent(`Safety Analysis Report - ${projectName}`);
        const body = encodeURIComponent(markdown.substring(0, 2000) + '\n\n[Full report available in Safety Companion]');
        window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
    };

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Link href="/">
                        <Button variant="ghost" size="icon" className="touch-target">
                            <ArrowLeft className="h-5 w-5" />
                        </Button>
                    </Link>
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight text-high-contrast">
                            Safety Reports
                        </h1>
                        <p className="text-muted-foreground mt-1">
                            View and download your JHA analysis reports
                        </p>
                    </div>
                </div>
                <Button
                    variant="outline"
                    size="sm"
                    onClick={() => refetch()}
                    className="gap-2"
                >
                    <RefreshCw className="h-4 w-4" />
                    Refresh
                </Button>
            </div>

            {/* Loading State */}
            {isLoading && (
                <div className="flex items-center justify-center py-12">
                    <div className="flex flex-col items-center gap-4">
                        <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        <p className="text-muted-foreground">Loading reports...</p>
                    </div>
                </div>
            )}

            {/* Error State */}
            {isError && (
                <Card className="border-red-500/30 bg-red-500/5">
                    <CardContent className="flex items-center gap-4 py-6">
                        <XCircle className="h-8 w-8 text-red-500" />
                        <div>
                            <h3 className="font-semibold">Failed to load reports</h3>
                            <p className="text-sm text-muted-foreground">Please try refreshing the page</p>
                        </div>
                        <Button variant="outline" onClick={() => refetch()} className="ml-auto">
                            Retry
                        </Button>
                    </CardContent>
                </Card>
            )}

            {/* Empty State */}
            {!isLoading && !isError && jhas.length === 0 && (
                <Card className="card-highlight">
                    <CardContent className="flex flex-col items-center justify-center py-12 text-center">
                        <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                            <FileText className="h-8 w-8 text-primary" />
                        </div>
                        <h3 className="text-xl font-semibold mb-2">No Reports Yet</h3>
                        <p className="text-muted-foreground mb-4 max-w-md">
                            Complete a JHA analysis to generate your first safety report.
                            Reports will appear here automatically.
                        </p>
                        <Link href="/jha/new">
                            <Button>Create New JHA</Button>
                        </Link>
                    </CardContent>
                </Card>
            )}

            {/* Reports List */}
            {!isLoading && jhas.length > 0 && (
                <div className="space-y-4">
                    {jhas.map((jha: any) => (
                        <Card
                            key={jha.id}
                            className={`transition-all duration-300 ${expandedReport === jha.id
                                    ? 'border-primary/50 shadow-lg'
                                    : 'hover:border-primary/30'
                                }`}
                        >
                            <CardHeader className="pb-3">
                                <div className="flex items-start justify-between gap-4">
                                    <div className="flex-1 min-w-0">
                                        <div className="flex items-center gap-3 mb-2">
                                            <Badge
                                                variant="outline"
                                                className={getDecisionColor(jha.go_no_go)}
                                            >
                                                {getDecisionIcon(jha.go_no_go)}
                                                <span className="ml-1">{jha.go_no_go?.replace('_', ' ') || 'PENDING'}</span>
                                            </Badge>
                                            {jha.risk_score && (
                                                <Badge variant="outline" className="bg-slate-500/10">
                                                    Risk: {jha.risk_score}%
                                                </Badge>
                                            )}
                                        </div>
                                        <CardTitle className="text-lg truncate">
                                            {jha.project_name || 'Untitled Analysis'}
                                        </CardTitle>
                                        <CardDescription className="flex items-center gap-2 mt-1">
                                            <Calendar className="h-3.5 w-3.5" />
                                            {jha.created_at ? format(new Date(jha.created_at), 'MMM d, yyyy h:mm a') : 'Unknown date'}
                                        </CardDescription>
                                    </div>

                                    {/* Action Buttons */}
                                    <div className="flex items-center gap-2">
                                        <Button
                                            variant="ghost"
                                            size="sm"
                                            onClick={() => toggleReport(jha.id)}
                                            className="gap-2"
                                        >
                                            {loadingMarkdown[jha.id] ? (
                                                <Loader2 className="h-4 w-4 animate-spin" />
                                            ) : (
                                                <Eye className="h-4 w-4" />
                                            )}
                                            {expandedReport === jha.id ? 'Hide' : 'View'}
                                            <ChevronDown className={`h-4 w-4 transition-transform ${expandedReport === jha.id ? 'rotate-180' : ''
                                                }`} />
                                        </Button>
                                        <Link href={`/jha/${jha.id}`}>
                                            <Button variant="outline" size="sm">
                                                Full Details
                                            </Button>
                                        </Link>
                                    </div>
                                </div>
                            </CardHeader>

                            {/* Expanded Report Content */}
                            {expandedReport === jha.id && (
                                <CardContent className="pt-0 border-t">
                                    {/* Action Bar */}
                                    <div className="flex items-center justify-end gap-2 py-3 border-b mb-4">
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            onClick={() => handleDownload(jha.id, jha.project_name)}
                                            disabled={!reportMarkdowns[jha.id]}
                                            className="gap-2"
                                        >
                                            <Download className="h-4 w-4" />
                                            Download
                                        </Button>
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            onClick={() => handleEmail(jha.id, jha.project_name)}
                                            disabled={!reportMarkdowns[jha.id]}
                                            className="gap-2"
                                        >
                                            <Mail className="h-4 w-4" />
                                            Email
                                        </Button>
                                    </div>

                                    {/* Markdown Content */}
                                    {loadingMarkdown[jha.id] ? (
                                        <div className="flex items-center justify-center py-8">
                                            <Loader2 className="h-6 w-6 animate-spin text-primary" />
                                        </div>
                                    ) : reportMarkdowns[jha.id] ? (
                                        <div className="rounded-lg bg-slate-50/50 dark:bg-slate-800/30 p-6 max-h-[600px] overflow-y-auto">
                                            <article className="prose prose-slate dark:prose-invert prose-sm max-w-none">
                                                <ReactMarkdown
                                                    components={{
                                                        h1: ({ children }) => (
                                                            <h1 className="text-xl font-bold text-slate-900 dark:text-slate-100 border-b pb-2 mb-4">
                                                                {children}
                                                            </h1>
                                                        ),
                                                        h2: ({ children }) => (
                                                            <h2 className="text-lg font-bold text-slate-800 dark:text-slate-200 mt-6 mb-3">
                                                                {children}
                                                            </h2>
                                                        ),
                                                        h3: ({ children }) => (
                                                            <h3 className="text-base font-semibold text-slate-700 dark:text-slate-300 mt-4 mb-2">
                                                                {children}
                                                            </h3>
                                                        ),
                                                        p: ({ children }) => (
                                                            <p className="text-slate-600 dark:text-slate-400 leading-relaxed mb-3">
                                                                {children}
                                                            </p>
                                                        ),
                                                        ul: ({ children }) => (
                                                            <ul className="list-disc list-outside ml-5 space-y-1 text-slate-600 dark:text-slate-400">
                                                                {children}
                                                            </ul>
                                                        ),
                                                        li: ({ children }) => (
                                                            <li className="leading-relaxed">{children}</li>
                                                        ),
                                                        strong: ({ children }) => (
                                                            <strong className="font-semibold text-slate-900 dark:text-slate-100">
                                                                {children}
                                                            </strong>
                                                        ),
                                                        hr: () => (
                                                            <hr className="border-t border-slate-200 dark:border-slate-700 my-4" />
                                                        ),
                                                    }}
                                                >
                                                    {reportMarkdowns[jha.id]}
                                                </ReactMarkdown>
                                            </article>
                                        </div>
                                    ) : (
                                        <p className="text-center text-muted-foreground py-4">
                                            Report content not available
                                        </p>
                                    )}
                                </CardContent>
                            )}
                        </Card>
                    ))}
                </div>
            )}

            {/* Quick Stats Footer */}
            {!isLoading && jhas.length > 0 && (
                <Card className="bg-slate-50/50 dark:bg-slate-800/30">
                    <CardContent className="py-4">
                        <div className="flex items-center justify-around text-center">
                            <div>
                                <p className="text-2xl font-bold text-primary">{jhas.length}</p>
                                <p className="text-xs text-muted-foreground">Total Reports</p>
                            </div>
                            <div className="h-8 w-px bg-border" />
                            <div>
                                <p className="text-2xl font-bold text-green-500">
                                    {jhas.filter((j: any) => j.go_no_go === 'GO').length}
                                </p>
                                <p className="text-xs text-muted-foreground">GO Decisions</p>
                            </div>
                            <div className="h-8 w-px bg-border" />
                            <div>
                                <p className="text-2xl font-bold text-yellow-500">
                                    {jhas.filter((j: any) => j.go_no_go === 'GO_WITH_CONDITIONS').length}
                                </p>
                                <p className="text-xs text-muted-foreground">Conditional</p>
                            </div>
                            <div className="h-8 w-px bg-border" />
                            <div>
                                <p className="text-2xl font-bold text-red-500">
                                    {jhas.filter((j: any) => j.go_no_go === 'NO_GO').length}
                                </p>
                                <p className="text-xs text-muted-foreground">NO GO</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            )}
        </div>
    );
}
