'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useJHADetails, useJHAProgress } from '@/hooks/use-api';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
    ArrowLeft,
    CheckCircle,
    WarningCircle,
    XCircle,
    ShieldCheck,
    FileText,
    DownloadSimple,
    FloppyDisk,
    ShareNetwork,
    Envelope,
    Check
} from '@phosphor-icons/react';
import { format } from 'date-fns';
import { ProgressTracker } from '@/components/jha/progress-tracker';
import { Agent1Card, Agent2Card, Agent3Card, Agent4Card, FullReportModule } from '@/components/analysis';
import { AnimatePresence, motion } from 'framer-motion';

export default function JHADetailPage() {
    const params = useParams();
    const router = useRouter();
    const id = params.id as string;


    const { data: jha, isLoading, isError } = useJHADetails(id);

    // Button states
    const [isSaving, setIsSaving] = useState(false);
    const [isSaved, setIsSaved] = useState(false);
    const [isCopied, setIsCopied] = useState(false);

    // Save to Reports
    const handleSaveToReports = async () => {
        if (!jha) return;
        setIsSaving(true);
        try {
            const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
            const response = await fetch(`${apiUrl}/api/v1/reports/save`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    analysisId: jha.id,
                    projectName: jha.project_name,
                    markdown: jha.markdown_report
                })
            });
            if (response.ok) {
                setIsSaved(true);
                setTimeout(() => setIsSaved(false), 3000);
            }
        } catch (error) {
            console.error('Save failed:', error);
        } finally {
            setIsSaving(false);
        }
    };

    // Share (copy link)
    const handleShare = async () => {
        if (!jha) return;
        try {
            const shareUrl = window.location.href;

            // Try Web Share API first (mobile)
            if (navigator.share) {
                await navigator.share({
                    title: `Safety Report - ${jha.project_name}`,
                    text: `JHA Analysis for ${jha.project_name}`,
                    url: shareUrl
                });
            } else {
                // Fallback to clipboard
                await navigator.clipboard.writeText(shareUrl);
                setIsCopied(true);
                setTimeout(() => setIsCopied(false), 2000);
            }
        } catch (error) {
            // User cancelled or failed, try clipboard
            try {
                await navigator.clipboard.writeText(window.location.href);
                setIsCopied(true);
                setTimeout(() => setIsCopied(false), 2000);
            } catch (e) {
                console.error('Share failed:', e);
            }
        }
    };

    // Email formatted report
    const handleEmailReport = () => {
        if (!jha) return;
        const subject = encodeURIComponent(`Safety Analysis Report - ${jha.project_name}`);
        const markdown = jha.markdown_report || generateEmailBody();
        const body = encodeURIComponent(markdown);
        window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
    };

    // Generate email body if no markdown available
    const generateEmailBody = () => {
        if (!jha) return '';
        const summary = jha.summary || {};
        const decision = summary.go_no_go_decision || 'PENDING';
        return `SAFETY ANALYSIS REPORT\n${'='.repeat(40)}\n\nProject: ${jha.project_name}\nDate: ${format(new Date(jha.created_at), 'PPP p')}\nDecision: ${decision}\nRisk Score: ${jha.risk_score || 'N/A'}%\n\nView full report: ${window.location.href}\n\n---\nGenerated by Safety Companion AI`;
    };

    if (isLoading) {
        return (
            <div className="flex h-[60vh] flex-col items-center justify-center p-4">
                <div className="relative flex h-20 w-20 flex-col items-center justify-center">
                    <div className="absolute inset-0 rounded-full border-2 border-primary/20 animate-[spin_3s_linear_infinite]" />
                    <div className="absolute inset-2 rounded-full border-2 border-primary/40 border-t-transparent animate-spin" />
                    <ShieldCheck className="h-8 w-8 text-primary animate-pulse" />
                </div>
                <div className="mt-8 text-center space-y-2">
                    <h3 className="text-sm font-black uppercase tracking-[0.2em] text-foreground">Initiating Secure Link</h3>
                    <p className="text-[10px] font-mono text-muted-foreground uppercase tracking-widest">Awaiting Handshake with Pipeline Core...</p>
                </div>
            </div>
        );
    }

    if (isError || !jha) {
        return (
            <div className="flex h-[50vh] flex-col items-center justify-center gap-4">
                <div className="rounded-full bg-destructive/10 p-4">
                    <XCircle className="h-8 w-8 text-destructive" />
                </div>
                <h2 className="text-xl font-semibold">Failed to load JHA</h2>
                <Button variant="outline" onClick={() => router.push('/jha')}>
                    Return to History
                </Button>
            </div>
        );
    }

    // Handle processing/error/failed states - use router.refresh instead of window.location.reload
    : start_line: 145
    // @ts-expect-error - status field not in strict type definition yet
    if (jha.status === 'processing' || jha.status === 'queued') {
        return <ProcessingView analysisId={id} onComplete={() => router.refresh()} />;
    }

    : start_line: 150
    // @ts-expect-error
    if (jha.status === 'error' || jha.status === 'failed' || jha.status === 'broken') {
        return (
            <div className="flex h-[50vh] flex-col items-center justify-center gap-4">
                <div className="rounded-full bg-orange-500/10 p-4">
                    <WarningCircle className="h-8 w-8 text-orange-500" />
                </div>
                <h2 className="text-xl font-semibold">Analysis Incomplete</h2>
                <p className="max-w-md text-center text-muted-foreground">
                    The analysis could not be fully completed. Some data may be missing.
                </p>
                {/* @ts-ignore */}
                {jha.error && (
                    <div className="mt-2 rounded bg-muted p-2 text-xs font-mono">
                        {/* @ts-ignore */}
                        {jha.error}
                    </div>
                )}
                <Button variant="outline" onClick={() => router.push('/jha')}>
                    Return to History
                </Button>
            </div>
        );
    }

    const getDecisionIcon = (decision: string) => {
        switch (decision) {
            case 'GO': return <CheckCircle className="h-6 w-6 text-green-500" />;
            case 'NO_GO': return <XCircle className="h-6 w-6 text-red-500" />;
            case 'GO_WITH_CONDITIONS': return <WarningCircle className="h-6 w-6 text-yellow-500" />;
            default: return <ShieldCheck className="h-6 w-6 text-muted-foreground" />;
        }
    };

    return (
        <div className="space-y-8 pb-12">
            {/* Header */}
            <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                <div>
                    <Button
                        variant="ghost"
                        size="sm"
                        className="mb-2 -ml-2 text-muted-foreground"
                        onClick={() => router.push('/jha')}
                    >
                        <ArrowLeft className="mr-2 h-4 w-4" />
                        Back to History
                    </Button>
                    <h1 className="text-3xl font-bold tracking-tight">{jha.project_name}</h1>
                    <div className="mt-2 flex items-center gap-4 text-sm text-muted-foreground">
                        <span className="flex items-center gap-1">
                            <FileText className="h-4 w-4" />
                            ID: {jha.id.slice(0, 8)}
                        </span>
                        <span>•</span>
                        <span>{format(new Date(jha.created_at), 'PPP p')}</span>
                    </div>
                </div>
                {/* Action Buttons */}
                <div className="flex flex-wrap items-center gap-2">
                    {/* Save to Reports */}
                    <Button
                        variant="default"
                        onClick={handleSaveToReports}
                        disabled={isSaving || isSaved}
                        className={`gap-2 ${isSaved ? 'bg-green-600 hover:bg-green-600' : ''}`}
                    >
                        {isSaved ? (
                            <>
                                <Check className="h-4 w-4" />
                                Saved!
                            </>
                        ) : (
                            <>
                                <FloppyDisk className="h-4 w-4" />
                                Save to Reports
                            </>
                        )}
                    </Button>

                    {/* Share */}
                    <Button
                        variant="outline"
                        onClick={handleShare}
                        className="gap-2"
                    >
                        {isCopied ? (
                            <>
                                <Check className="h-4 w-4 text-green-500" />
                                Copied!
                            </>
                        ) : (
                            <>
                                <ShareNetwork className="h-4 w-4" />
                                Share
                            </>
                        )}
                    </Button>

                    {/* Email Report */}
                    <Button
                        variant="outline"
                        onClick={handleEmailReport}
                        className="gap-2"
                    >
                        <Envelope className="h-4 w-4" />
                        Email
                    </Button>

                    {/* Export PDF */}
                    <Button variant="outline" className="gap-2">
                        <DownloadSimple className="h-4 w-4" />
                        Export PDF
                    </Button>
                </div>
            </div>

            {/* Executive Summary */}
            <div className="grid gap-6 md:grid-cols-2">
                <Card className="md:col-span-2">
                    <CardHeader className="pb-2">
                        <CardTitle>Executive Summary</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between">
                            <div className="flex items-center gap-4">
                                {getDecisionIcon(jha.urgency_level)}
                                <div>
                                    <p className="text-sm font-medium text-muted-foreground">Decision</p>
                                    <h3 className="text-2xl font-bold">
                                        {jha.urgency_level === 'CRITICAL' || jha.urgency_level === 'HIGH' ? 'NO GO' : 'GO'}
                                        <span className="ml-2 text-base font-normal text-muted-foreground">
                                            ({jha.urgency_level})
                                        </span>
                                    </h3>
                                </div>
                            </div>

                            <div className="md:text-right">
                                <p className="text-sm font-medium text-muted-foreground">Risk Score</p>
                                <div className="flex items-center gap-2 md:justify-end">
                                    <h3 className="text-3xl font-bold">{jha.risk_score}</h3>
                                    <span className="text-muted-foreground">/ 100</span>
                                </div>
                            </div>
                        </div>

                        {/* Executive Summary Details */}
                        {jha.agent_outputs?.agent4_final_report?.executiveSummary && (
                            <div className="mt-6 pt-6 border-t">
                                {/* Handle both string and object formats */}
                                {typeof jha.agent_outputs.agent4_final_report.executiveSummary === 'string' ? (
                                    <p className="text-muted-foreground leading-relaxed whitespace-pre-wrap">
                                        {jha.agent_outputs.agent4_final_report.executiveSummary}
                                    </p>
                                ) : (
                                    <div className="space-y-3">
                                        {/* Top Threats */}
                                        {jha.agent_outputs.agent4_final_report.executiveSummary.topThreats?.length > 0 && (
                                            <div>
                                                <h4 className="text-sm font-medium mb-2">Top Threats</h4>
                                                <ul className="space-y-1">
                                                    {jha.agent_outputs.agent4_final_report.executiveSummary.topThreats.map((threat: string, idx: number) => (
                                                        <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                                                            <span className="text-red-500">⚠</span> {threat}
                                                        </li>
                                                    ))}
                                                </ul>
                                            </div>
                                        )}
                                        {/* Critical Actions */}
                                        {jha.agent_outputs.agent4_final_report.executiveSummary.criticalActions?.length > 0 && (
                                            <div>
                                                <h4 className="text-sm font-medium mb-2">Critical Actions Required</h4>
                                                <ul className="space-y-1">
                                                    {jha.agent_outputs.agent4_final_report.executiveSummary.criticalActions.map((action: string, idx: number) => (
                                                        <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                                                            <span className="text-orange-500">→</span> {action}
                                                        </li>
                                                    ))}
                                                </ul>
                                            </div>
                                        )}
                                        {/* Incident Probability */}
                                        {jha.agent_outputs.agent4_final_report.executiveSummary.incidentProbability !== undefined && (
                                            <p className="text-sm text-muted-foreground">
                                                <span className="font-medium">Incident Probability (next 4hrs):</span>{' '}
                                                {jha.agent_outputs.agent4_final_report.executiveSummary.incidentProbability}%
                                            </p>
                                        )}
                                    </div>
                                )}
                            </div>
                        )}

                        {/* Critical Findings */}
                        {jha.agent_outputs?.agent4_final_report?.criticalFindings?.length > 0 && (
                            <div className="mt-6 pt-6 border-t">
                                <h4 className="font-medium mb-3 flex items-center gap-2">
                                    <WarningCircle className="h-4 w-4 text-orange-500" />
                                    Critical Findings
                                </h4>
                                <ul className="space-y-2">
                                    {jha.agent_outputs.agent4_final_report.criticalFindings.map((finding: string, idx: number) => (
                                        <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                                            <span className="text-orange-500 mt-1">•</span>
                                            {finding}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {/* Stop Work Conditions */}
                        {jha.agent_outputs?.agent4_final_report?.stopWorkConditions?.length > 0 && (
                            <div className="mt-6 pt-6 border-t">
                                <h4 className="font-medium mb-3 flex items-center gap-2">
                                    <XCircle className="h-4 w-4 text-red-500" />
                                    Stop Work Conditions
                                </h4>
                                <ul className="space-y-2">
                                    {jha.agent_outputs.agent4_final_report.stopWorkConditions.map((condition: string, idx: number) => (
                                        <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                                            <span className="text-red-500 mt-1">•</span>
                                            {condition}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}
                    </CardContent>
                </Card>

                {/* Primary Safety Categories */}
                {jha.safety_categories && jha.safety_categories.length > 0 && (
                    <Card>
                        <CardHeader>
                            <CardTitle className="text-base">Safety Categories</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="flex flex-wrap gap-2">
                                {jha.safety_categories.map((cat: string) => (
                                    <Badge key={cat} variant="secondary" className="capitalize">
                                        {cat.replace(/_/g, ' ')}
                                    </Badge>
                                ))}
                            </div>
                        </CardContent>
                    </Card>
                )}
            </div>

            {/* Agent 1: Data Quality Assessment */}
            {jha.agent_outputs?.agent1_validation && (
                <Agent1Card data={jha.agent_outputs.agent1_validation} />
            )}

            {/* Agent 2: Risk Assessment */}
            {jha.agent_outputs?.agent2_risk_assessment && (
                <Agent2Card data={jha.agent_outputs.agent2_risk_assessment.riskProfile || jha.agent_outputs.agent2_risk_assessment} />
            )}

            {/* Agent 3: Swiss Cheese & Incident Prediction */}
            {jha.agent_outputs?.agent3_swiss_cheese && (
                <Agent3Card data={jha.agent_outputs.agent3_swiss_cheese} />
            )}
            {/* Agent 4: Synthesized Action Plan & Compliance */}
            {jha.agent_outputs?.agent4_final_report && (
                <Agent4Card data={jha.agent_outputs.agent4_final_report} />
            )}

            {/* Full Report Module - Complete formatted report with actions */}
            {jha.markdown_report && (
                <FullReportModule
                    markdown={jha.markdown_report}
                    analysisId={jha.id}
                    projectName={jha.project_name}
                />
            )}
        </div>
    );
}

// Processing View Component - shows SSE-powered progress tracker
function ProcessingView({ analysisId, onComplete }: { analysisId: string; onComplete: () => void }) {
    const progress = useJHAProgress(analysisId);

    useEffect(() => {
        if (progress.status === 'completed') {
            // Small delay to show completion before reloading
            const timer = setTimeout(onComplete, 1500);
            return () => clearTimeout(timer);
        }
        return undefined;
    }, [progress.status, onComplete]);

    return (
        <div className="flex min-h-[70vh] flex-col items-center justify-center py-12 px-4">
            <ProgressTracker
                currentAgent={progress.currentAgent}
                agentStatus={progress.agentStatus}
                progress={progress.progress}
                elapsedMs={progress.elapsedMs}
            />

            <AnimatePresence>
                {progress.status === 'error' && progress.error && (
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-8 w-full max-w-md p-4 bg-destructive/10 border border-destructive/20 rounded-xl text-destructive text-sm font-medium flex items-start gap-3 shadow-lg"
                    >
                        <WarningCircle className="h-5 w-5 flex-shrink-0" />
                        <div className="space-y-1">
                            <p className="font-black uppercase tracking-widest text-[10px]">Pipeline Interrupted</p>
                            <p className="opacity-80 text-xs leading-relaxed">{progress.error}</p>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
